wtds/profile/urls.py
from django.conf.urls import patterns, include, url

from .views import (AccountView, UploadsView, FavoriteListView, FavoriteCreateView,
        FavoriteDeleteView, ProfileSwitchView, ProfileDeactivateView)

urlpatterns = patterns('',
    url(r'^$', AccountView.as_view(self_view=True), name='view'),
    url(r'^uploads/$', UploadsView.as_view(), name='uploads'),
    url(r'^favorites/', include(patterns('',
        url(r'^$', FavoriteListView.as_view(), name='list'),
        url(r'^(?P<pk>\d+)/add/$', FavoriteCreateView.as_view(), name='add'),
        url(r'^(?P<pk>\d+)/remove/$', FavoriteDeleteView.as_view(), name='remove'),
    ), namespace="favorites")),
    url(r'^switch/$', ProfileSwitchView.as_view(), name='switch'),
    url(r'^off/$', ProfileDeactivateView.as_view(), name='deactivate'),
)

wtds/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
# from django.contrib import admin

from .views import HomeView

# admin.autodiscover()

handler403 = 'wtds.core.views.handler403'
handler404 = 'wtds.core.views.handler404'
handler500 = 'wtds.core.views.handler500'

urlpatterns = patterns('',
    url(r'^api/', include('wtds.urls_api')),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^', include('wtds.wallpapers.urls')),
    url(r'^account/', include('wtds.profile.urls', namespace="profile")),
    url(r'^reports/', include('wtds.reports.management_urls', namespace="reports")),
    
    # auth
    url(r'^', include(patterns('',
        url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
        url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('home')}, name="logout"),
        url(r'^', include('django.contrib.auth.urls')),
    ), namespace='auth')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^~/403/$', handler403, {'fake': True}),
    url(r'^~/404/$', handler404, {'fake': True}),
    url(r'^~/500/$', handler500, {'fake': True}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^{}(?P<path>.*)$'.format(settings.MEDIA_URL.lstrip('/')), 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        })
    )

wtds/profile/models.py
# coding=utf-8

import logging
from decimal import Decimal

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from wtds.wallpapers.constants import PURITY_CHOICES
from .managers import ProfileManager, FavoriteManager
from .validators import is_ratio

logger = logging.getLogger(__name__)

FILTER_STYLE_CHOICES = (
    ('exact', 'only'),
    ('lte', 'at most'),
    ('gte', 'at least'),
)
FILTER_STYLE_MATHEMATIC_CHOICES = {
    'exact': '=',
    'lte': '<',
    'gte': '>',
}

class Profile(models.Model):
    """
    Each user may maintain multiple profiles to allow different default settings for searches,
    filters, and purity ratings.
    
    """
    
    objects = ProfileManager()

    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    name = models.CharField(_('name'), max_length=100, blank=True)
    is_active = models.BooleanField(_('active'), default=False)

    purity_rating = models.IntegerField(_('purity'), choices=PURITY_CHOICES, default=0)
    purity_style = models.CharField(choices=FILTER_STYLE_CHOICES, max_length=10, default="lte")
    ratio = models.CharField(_('ratio'), validators=[is_ratio], max_length=10, blank=True)
    ratio_style = models.CharField(choices=FILTER_STYLE_CHOICES, max_length=10, default="gte")
    width = models.PositiveIntegerField(_('width'), blank=True, null=True)
    width_style = models.CharField(choices=FILTER_STYLE_CHOICES, max_length=10, default="gte")
    height = models.PositiveIntegerField(_('height'), blank=True, null=True)
    height_style = models.CharField(choices=FILTER_STYLE_CHOICES, max_length=10, default="gte")

    class Meta:
        ordering = ('name', '-id')

    def __str__(self):
        if self.id is None:
            return "[Default]"
        if self.name:
            return self.name
        bits = [self.get_purity_style_display(), self.get_purity_rating_display()]
        if self.ratio:
            bits.append(self.get_ratio_display())
        if self.width or self.height:
            bits.append("[{} × {}]".format(self.get_width_display(), self.get_height_display()))
        return " ".join(bits)

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        if self.is_active:
            self.user.profile_set.exclude(id=self.id).update(is_active=False)

    def make_active(self):
        self.is_active = True
        self.save()

    def get_fractional_ratio(self):
        """ Returns a floating-point number that is ratio.x / ratio.y """
        if self.ratio:
            x, y = map(Decimal, self.ratio.split(':'))
            return x / y

    def get_ratio_style_mathematic_display(self):
        return FILTER_STYLE_MATHEMATIC_CHOICES[self.ratio_style]

    def get_width_style_mathematic_display(self):
        return FILTER_STYLE_MATHEMATIC_CHOICES[self.width_style]

    def get_height_style_mathematic_display(self):
        return FILTER_STYLE_MATHEMATIC_CHOICES[self.height_style]

    def get_ratio_display(self):
        if self.ratio:
            if self.ratio_style == "exact":
                matching = "@"
            else:
                matching = self.get_ratio_style_mathematic_display()
            return "{}{}".format(matching, self.ratio)
        return "*"

    def get_width_display(self):
        if self.width:
            if self.width_style == "exact":
                return str(self.width)
            else:
                return "{}{}".format(self.get_width_style_mathematic_display(), self.width)
        return "*"

    def get_height_display(self):
        if self.height:
            if self.height_style == "exact":
                return str(self.height)
            else:
                return "{}{}".format(self.get_height_style_mathematic_display(), self.height)
        return "*"

class Favorite(models.Model):

    objects = FavoriteManager()

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    wallpaper = models.ForeignKey('wallpapers.Wallpaper')
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_created',)
    

wtds/profile/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'optional'}),
            'ratio_style': forms.Select(attrs={'tabindex': -1}),
            'width_style': forms.Select(attrs={'tabindex': -1}),
            'height_style': forms.Select(attrs={'tabindex': -1}),
        }
    

class ProfileSwitchForm(forms.Form):
    profile = forms.ModelChoiceField(queryset=Profile.objects.none(), empty_label=str(Profile()))

    def __init__(self, user, *args, **kwargs):
        super(ProfileSwitchForm, self).__init__(*args, **kwargs)

        profiles = user.profile_set.all()
        self.fields['profile'].queryset = profiles
        self.fields['profile'].initial = user.active_profile

wtds/profile/views.py
import logging

from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.defaultfilters import pluralize
from django.utils.translation import ungettext, ugettext_lazy as _

from extra_views import InlineFormSetView

from wtds.core.views import AuthenticationMixin
from wtds.wallpapers.models import Wallpaper
from .models import Profile, Favorite
from .forms import ProfileSwitchForm, ProfileForm

logger = logging.getLogger(__name__)

class AccountView(InlineFormSetView):
    model = User
    inline_model = Profile
    extra = 1
    template_name = "profiles/profiles.html"

    form_class = ProfileForm

    self_view = False
    section = "profiles"

    def get_object(self):
        if self.self_view: # no 'pk' or 'slug' in the url kwargs
            return self.request.user
        return super(AccountView, self).get_object()

    def formset_valid(self, formset):
        total_profiles = formset.initial_form_count()
        response = super(AccountView, self).formset_valid(formset)

        updated_count = len(formset.changed_objects)
        deleted_count = len(formset.deleted_objects)

        if updated_count:
            msg = ungettext(
                "Updated profile",
                "Updated %(count)d profiles",
                updated_count
            ) % {'count': updated_count}
            messages.success(self.request, msg)
        if deleted_count:
            msg = ungettext(
                "Deleted profile.",
                "Deleted %(count)d profiles.",
                deleted_count,
            ) % {'count': deleted_count}
            messages.success(self.request, msg)
        if not any((updated_count, deleted_count)):
            messages.info(self.request, _("No changes."))

        return response

    def formset_invalid(self, formset):
        response = super(AccountView, self).formset_invalid(formset)
        messages.error(self.request, _("Oops, something went wrong."))
        return response

    def get_context_data(self, **kwargs):
        context = super(AccountView, self).get_context_data(**kwargs)
        context.update({
            'total_uploads': self.request.user.wallpaper_set.count(),
            'uploads': self.request.user.wallpaper_set.filter_for_user(self.request.user),
        })
        return context

class UploadsView(ListView):
    template_name = "profiles/upload_list.html"
    section = "uploads"

    def get_queryset(self):
        return self.request.user.wallpaper_set.filter_from_request(self.request.GET) \
                .filter_for_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super(UploadsView, self).get_context_data(**kwargs)
        context['total'] = self.request.user.wallpaper_set.count()
        return context

class FavoriteListView(ListView):
    template_name = "profiles/favorite_list.html"
    section = "favorites"

    def get_queryset(self):
        return self.request.user.favorite_set.filter_from_request(self.request.GET) \
                .select_related('wallpaper').filter_for_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super(FavoriteListView, self).get_context_data(**kwargs)
        context['total'] = self.request.user.favorite_set.count()
        return context

class FavoriteCreateView(AuthenticationMixin, DetailView):
    model = Wallpaper

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.favorite_set.get_or_create(user=self.request.user)
        return HttpResponseRedirect(obj.get_absolute_url())

class FavoriteDeleteView(AuthenticationMixin, DetailView):
    model = Wallpaper

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        success_url = obj.get_absolute_url()
        try:
            favorite = obj.favorite_set.get(user=self.request.user)
        except Wallpaper.DoesNotExist:
            pass
        else:
            favorite.delete()
        return HttpResponseRedirect(success_url)

class ProfileSwitchView(FormMixin, View):
    """ POST-only view for setting the profile via a ``ProfileSwitchForm`` submission. """

    form_class = ProfileSwitchForm # Form for listing the user's available profiles

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form_kwargs(self):
        """ Adds ``user`` to form constructor arguments. """
        kwargs = super(ProfileSwitchView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return self.request.GET.get('next', '/')

    def form_valid(self, form):
        """ Make the profile active, redirect to where they came from. """
        form.cleaned_data['profile'].make_active()
        return super(ProfileSwitchView, self).form_valid(form)

    def form_invalid(self, form):
        """ If none-value, deactivate.  Redirect as if it worked. """
        if not form['profile'].value():
            self.request.user.profile_set.deactivate()
        return super(ProfileSwitchView, self).form_valid(form)

class ProfileDeactivateView(View):
    def get(self, request):
        self.request.user.profile_set.deactivate()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return self.request.GET.get('next', '/')

wtds/profile/templates/profiles/base.html
{% extends "base.html" %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/profiles.css" type="text/css" />
{% endblock css %}

{% block content %}
    <div id="page-changer">
        <a id="page-profiles"
                class="tooltip{% if view.section == "profiles" %} active{% endif %}"
                href="{% url "profile:view" %}">
            <span>{% trans "Profiles" %}</span>
        </a>
        <a id="page-uploads"
                class="tooltip{% if view.section == "uploads" %} active{% endif %}"
                href="{% url "profile:uploads" %}">
            <span>{% trans "Uploads" %}</span>
        </a>
        <a id="page-favorites"
                class="tooltip{% if view.section == "favorites" %} active{% endif %}"
                href="{% url "profile:favorites:list" %}">
            <span>{% trans "Favorites" %}</span>
        </a>
    </div>
{% endblock content %}

wtds/profile/templates/profiles/favorite_list.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block search %}
    {% include "wallpapers/includes/search_bar.html" %}
{% endblock search %}

{% block content %}
    {{ block.super }}
    <h2>
        {% trans "Your favorites" %}
        {% if total == object_list|length %}
            ({{ object_list|length }})
        {% else %}
            (profile filtered: {{ object_list|length }}/{{ total }})
        {% endif %}
    </h2>
    <div id="lineup">
        {% for favorite in object_list %}
            {% include "wallpapers/includes/tile.html" with wallpaper=favorite.wallpaper only %}
        {% endfor %}
    </div>
{% endblock content %}

wtds/profile/templates/profiles/favorites.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block content %}
    {{ block.super }}
    <h2>
        {% trans "Your favorites" %}
        {% if total == object_list|length %}
            ({{ object_list|length }})
        {% else %}
            (profile filtered: {{ object_list|length }}/{{ total }})
        {% endif %}
    </h2>
    {% for favorite in object_list %}
        {% include "wallpapers/includes/tile.html" with wallpaper=favorite.wallpaper only %}
    {% endfor %}
{% endblock content %}

wtds/profile/templates/profiles/profiles.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" type="text/css" />
{% endblock css %}

{% block content %}
    {{ block.super }}
    <div id="profiles">
        <h2>{% trans "Profiles" %}</h2>
        <p class="description">
            {% blocktrans %}
            Select your default content settings. The active profile filters all wallpapers,
            including searches, suggestions, and your own list of uploads. If no profile is
            activated, the default clean profile is automatically be used. Changing the drop-down
            at the upper right on any page will instantly activate a new profile.
            {% endblocktrans %}
        </p>
        <form action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <div id="actions">
                <div class="buttons-strip">
                    <button rel="confirm" type="submit" title="{% trans "Save" %}"><span></span> {% trans "Save" %}</button>
                </div>
            </div>
            {% for form in formset %}
                {% with profile=form.instance %}
                {% if forloop.counter0 == formset.initial_form_count %}
                    <h2>{% trans "Add a new profile" noop %}:</h2>
                {% endif %}
                <fieldset class="{{ profile.get_purity_rating_display|slugify }} {{ profile.get_purity_style_display|slugify }}{% if profile.is_active %} active{% endif %}">
                    <legend>
                        <label for="{{ form.is_active.auto_id }}">
                            {{ form.is_active }}
                            {{ form.instance }}
                        </label>
                    </legend>
                    <div class="DELETE">{{ form.DELETE.label_tag }} {{ form.DELETE }}</div>
                    {% for field in form.hidden_fields %}{{ field }}{% endfor %}
                    <p>{{ form.purity_rating.label_tag }} {{ form.purity_style }} {{ form.purity_rating }}</p>

                    {% if form.ratio.errors %}<ul class="errorlist">{{ form.ratio.errors|unordered_list }}</ul>{% endif %}
                    <p rel="ratio">{{ form.ratio.label_tag }} {{ form.ratio_style }} {{ form.ratio }}</p>

                    {% if form.width.errors %}<ul class="errorlist">{{ form.width.errors|unordered_list }}</ul>{% endif %}
                    {% if form.height.errors %}<ul class="errorlist">{{ form.height.errors|unordered_list }}</ul>{% endif %}
                    <p rel="dimensions">
                        <label for="{{ form.width.auto_id }}">Dimensions</label>
                        {{ form.width_style }} {{ form.width }} &#x00D7; {{ form.height_style }} {{ form.height }}
                    </p>
                    <p>{{ form.name.label_tag }} {{ form.name }}</p>
                </fieldset>
                {% endwith %}
            {% endfor %}
        </form>
    </div>

    <div id="user-data">
        <div id="uploads">
            <h2>
                {% trans "Your uploads" %}
                {% if total_uploads == uploads|length %}
                    ({{ uploads|length }})
                {% else %}
                    (profile filtered: {{ uploads|length }}/{{ total_uploads }})
                {% endif %}
            </h2>
            {% for wallpaper in uploads %}
                {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

wtds/profile/templates/profiles/profiles_formset.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" type="text/css" />
{% endblock css %}

{% block content %}
    {{ block.super }}
    <div id="profiles">
        <h2>{% trans "Profiles" %}</h2>
        <p class="description">
            {% blocktrans %}
            Select your default content settings. The active profile filters all wallpapers,
            including searches, suggestions, and your own list of uploads. If no profile is
            activated, the default clean profile is automatically be used. Changing the drop-down
            at the upper right on any page will instantly activate a new profile.
            {% endblocktrans %}
        </p>
        <form action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <div id="actions">
                <div class="buttons-strip">
                    <button rel="confirm" type="submit" title="{% trans "Save" %}"><span></span> {% trans "Save" %}</button>
                </div>
            </div>
            {% for form in formset %}
                {% with profile=form.instance %}
                {% if forloop.counter0 == formset.initial_form_count %}
                    <h2>{% trans "Add a new profile" noop %}:</h2>
                {% endif %}
                <fieldset class="{{ profile.get_purity_rating_display|slugify }} {{ profile.get_purity_style_display|slugify }}{% if profile.is_active %} active{% endif %}">
                    <legend>
                        <label for="{{ form.is_active.auto_id }}">
                            {{ form.is_active }}
                            {{ form.instance }}
                        </label>
                    </legend>
                    <div class="DELETE">{{ form.DELETE.label_tag }} {{ form.DELETE }}</div>
                    {% for field in form.hidden_fields %}{{ field }}{% endfor %}
                    <p>{{ form.purity_rating.label_tag }} {{ form.purity_style }} {{ form.purity_rating }}</p>

                    {% if form.ratio.errors %}<ul class="errorlist">{{ form.ratio.errors|unordered_list }}</ul>{% endif %}
                    <p rel="ratio">{{ form.ratio.label_tag }} {{ form.ratio_style }} {{ form.ratio }}</p>

                    {% if form.width.errors %}<ul class="errorlist">{{ form.width.errors|unordered_list }}</ul>{% endif %}
                    {% if form.height.errors %}<ul class="errorlist">{{ form.height.errors|unordered_list }}</ul>{% endif %}
                    <p rel="dimensions">
                        <label for="{{ form.width.auto_id }}">Dimensions</label>
                        {{ form.width_style }} {{ form.width }} &#x00D7; {{ form.height_style }} {{ form.height }}
                    </p>
                    <p>{{ form.name.label_tag }} {{ form.name }}</p>
                </fieldset>
                {% endwith %}
            {% endfor %}
        </form>
    </div>

    <div id="user-data">
        <div id="uploads">
            <h2>
                {% trans "Your uploads" %}
                {% if total_uploads == uploads|length %}
                    ({{ uploads|length }})
                {% else %}
                    (profile filtered: {{ uploads|length }}/{{ total_uploads }})
                {% endif %}
            </h2>
            {% for wallpaper in uploads %}
                {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

wtds/profile/templates/profiles/upload_list.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block search %}
    {% include "wallpapers/includes/search_bar.html" %}
{% endblock search %}

{% block content %}
    {{ block.super }}
    <h2>
        {% trans "Your uploads" %}
        {% if total == object_list|length %}
            ({{ object_list|length }})
        {% else %}
            (profile filtered: {{ object_list|length }}/{{ total }})
        {% endif %}
    </h2>
    <div id="lineup">
        {% for wallpaper in object_list %}
            {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
        {% endfor %}
    </div>
{% endblock content %}

wtds/profile/templates/profiles/uploads.html
{% extends "profiles/base.html" %}
{% load i18n %}

{% block content %}
    {{ block.super }}
    <h2>
        {% trans "Your uploads" %}
        {% if total == object_list|length %}
            ({{ object_list|length }})
        {% else %}
            (profile filtered: {{ object_list|length }}/{{ total }})
        {% endif %}
    </h2>
    {% for wallpaper in object_list %}
        {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
    {% endfor %}
{% endblock content %}