wtds/profile/urls.py
from django.conf.urls import patterns, include, url

from .views import (AccountView, UploadsView, FavoriteListView, FavoriteCreateView,
        FavoriteDeleteView, ProfileSwitchView, ProfileDeactivateView)

urlpatterns = patterns('',
    url(r'^$', AccountView.as_view(self_view=True), name='view'),
    url(r'^uploads/$', UploadsView.as_view(), name='uploads'),
    url(r'^favorites/', include(patterns('',
        url(r'^$', FavoriteListView.as_view(), name='list'),
        url(r'^(?P<pk>\d+)/add/$', FavoriteCreateView.as_view(), name='add'),
        url(r'^(?P<pk>\d+)/remove/$', FavoriteDeleteView.as_view(), name='remove'),
    ), namespace="favorites")),
    url(r'^switch/$', ProfileSwitchView.as_view(), name='switch'),
    url(r'^off/$', ProfileDeactivateView.as_view(), name='deactivate'),
)

wtds/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
# from django.contrib import admin

from .views import HomeView

# admin.autodiscover()

handler403 = 'wtds.core.views.handler403'
handler404 = 'wtds.core.views.handler404'
handler500 = 'wtds.core.views.handler500'

urlpatterns = patterns('',
    url(r'^api/', include('wtds.urls_api')),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^', include('wtds.wallpapers.urls')),
    url(r'^account/', include('wtds.profile.urls', namespace="profile")),
    url(r'^reports/', include('wtds.reports.management_urls', namespace="reports")),
    
    # auth
    url(r'^', include(patterns('',
        url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
        url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('home')}, name="logout"),
        url(r'^', include('django.contrib.auth.urls')),
    ), namespace='auth')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^~/403/$', handler403, {'fake': True}),
    url(r'^~/404/$', handler404, {'fake': True}),
    url(r'^~/500/$', handler500, {'fake': True}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^{}(?P<path>.*)$'.format(settings.MEDIA_URL.lstrip('/')), 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        })
    )

wtds/wallpapers/urls.py
from django.conf.urls import patterns, url, include

from wtds.reports import include_reports_urls
from .views import (WallpaperCreateView, WallpaperUpdateView, WallpaperDetailView,
        WallpaperDeleteView, WallpaperListView, TagListView, TagOrphanedListView, TagUpdateView,
        TagDeleteView, TagAutocompleteView)

urlpatterns = patterns('',
    url(r'^wallpapers/', include(patterns('',
        # Filtered views
        url(r'^$', WallpaperListView.as_view(), name="list"),
        url(r'^(?P<ratio>\d+:\d+)/$', WallpaperListView.as_view(), name="list"),

        # Special filtered views
        url(r'^in-danger/', include(patterns('',
            url(r'^$', WallpaperListView.as_view(in_danger=True), name="in_danger"),
            url(r'^(?P<slug>[\w-]+)/$', WallpaperListView.as_view(in_danger=True), name="in_danger"),
        ))),

        url(r'^new/$', WallpaperCreateView.as_view(), name="upload"),
        url(r'^(?P<pk>\d+)/', include(patterns('',
            url(r'^$', WallpaperDetailView.as_view(), name="view"),
            url(r'^download/$', WallpaperDetailView.as_view(download=True), name="download"),
            url(r'^edit/$', WallpaperUpdateView.as_view(), name="edit"),
            url(r'^delete/$', WallpaperDeleteView.as_view(), name="delete"),
        ))),

        # Reports
        include_reports_urls('wallpaper'),
        # url(r'^reports/', include('wtds.reports.urls', namespace="reports", app_name='wallpapers')),
    ), namespace="wallpapers")),

    url(r'^tags/', include(patterns('',
        url(r'^$', TagListView.as_view(), name="list"),
        url(r'^orphaned/$', TagOrphanedListView.as_view(), name="orphaned"),
        url(r'^autocomplete/$', TagAutocompleteView.as_view(), name="autocomplete"),
        url(r'^inspect/(?P<slug>[\w-]+)/', include(patterns('',
            url(r'^edit/$', TagUpdateView.as_view(), name="edit"),
            url(r'^delete/$', TagDeleteView.as_view(), name="delete"),
        ))),
    ), namespace="tags")),
)

wtds/core/models.py
# Required for Django to recognize this app as a valid templatetag library source

wtds/wallpapers/models.py
from fractions import gcd
import random
from operator import itemgetter
import logging
from decimal import Decimal

from django.db import models
from django.db.models import Avg, F
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.generic import GenericRelation
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from taggit.models import TagBase, GenericTaggedItemBase
from taggit.managers import TaggableManager

from wtds.reports import ReportsManager
from .managers import TagManager, WallpaperManager
from .constants import (COMMON_ASPECT_RATIOS, FRIENDLY_ASPECT_RATIOS, RANDOM_STACK_TILT_ANGLES,
        PURITY_CHOICES, MIN_PURITY_RATING, MAX_PURITY_RATING)

logger = logging.getLogger(__name__)

class Tag(TagBase):
    """ Adds a purity rating to the existing taggit ``Tag`` model. """
    purity_rating = models.FloatField(_('purity rating'), default=0, editable=False)

    objects = TagManager()

    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('wallpapers:list') + "?tag={}".format(self.slug)
    
    def get_wallpapers(self):
        """ Due to the generic relation between this and ``Wallpaper`` this method eases lookup. """
        return Wallpaper.objects.filter(tags=self)
    
    def get_wallpapers_with_this_tag_only(self):
        """ Returns ``Wallpaper`` objects whose only tag is this one. """
        return Wallpaper.objects.filter_by_orphan_danger(tags=self)

    def get_purity_rating_display(self):
        """ Fakes the normal API for a ``choices`` field. """
        try:
            return PURITY_CHOICES[int(round(self.purity_rating))][1]
        except IndexError:
            rating = self.purity_rating
            self.purity_rating = min(max(self.purity_rating, MIN_PURITY_RATING), MAX_PURITY_RATING)
            logger.error("Tag %r has a purity rating %r outside of the valid range %d-%d."
                    "Normalizing to %d.", self, rating, MIN_PURITY_RATING, MAX_PURITY_RATING,
                    self.purity_rating)
            self.save()

class TaggedWallpaper(GenericTaggedItemBase):
    """ A replacement ``Tag`` model for taggit's API. """
    tag = models.ForeignKey('Tag', related_name="%(app_label)s_%(class)s_items")

class Wallpaper(models.Model):
    objects = WallpaperManager()

    name = models.CharField(_('Name'), max_length=100, blank=True,
            help_text=_("If left blank, the tags will be shown."))
    image = models.ImageField(_('Image'), upload_to='%Y/%m/%d', height_field='height',
            width_field='width')
    height = models.PositiveIntegerField(_('Height'))
    width = models.PositiveIntegerField(_('Width'))
    raw_ratio = models.CharField(max_length=50)
    fractional_ratio = models.DecimalField(max_digits=11, decimal_places=10)
    # color_profile = models.CharField()

    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('uploader'),
            help_text=_("Contributing user account"))
    author = models.ForeignKey('Author', verbose_name=_('Author'), blank=True, null=True,
            help_text=_("Original creator"))
    license = models.ForeignKey('License', verbose_name=_('License'), default=8)
    duplicate_of = models.ForeignKey('self', verbose_name=_('Duplicate'), blank=True, null=True)
    date_created = models.DateTimeField(_('Date created'), auto_now_add=True)
    is_public = models.BooleanField(_('Public'), default=True)
    purity_rating = models.IntegerField(_('Purity'), choices=PURITY_CHOICES, default=0)

    views = models.PositiveIntegerField(_('Views'), default=0)
    tags = TaggableManager(_('Tags'), blank=False, through=TaggedWallpaper)

    reports = ReportsManager()

    class Meta:
        get_latest_by = 'date_created'

    def __str__(self):
        if self.name:
            return self.name
        return ", ".join(map(str, self.tags.all()))

    def clean(self):
        if self.duplicate_of and self.duplicate_of is self:
            raise ValidationError("Wallpaper can't be marked as a duplicate of itself.")

    def save(self, *args, **kwargs):
        """ Pre-bake the ratio. """
        self.raw_ratio = self.get_aspect_ratio()
        self.fractional_ratio = self.get_fractional_aspect_ratio()
        super(Wallpaper, self).save(*args, **kwargs)

    def assess_tag_purity(self):
        """ Visits each tag and crunches the average purity rating of its wallpapers. """
        return
        # AVG = Avg('wallpapers_taggedwallpaper_items__wallpaper__purity_rating')
        # tags = self.tags.annotate(purity_avg=AVG).exclude(purity_avg=F('purity_rating'))
        # for tag in tags:
        #     logger.info("Tag %r changing purity rating from %r to %r", tag, tag.purity_rating,
        #             tag.purity_avg)
        #     tag.purity_rating = tag.purity_avg
        #     tag.save()

    def get_absolute_url(self):
        return reverse('wallpapers:view', kwargs={'pk': self.pk})

    def get_download_url(self):
        return reverse('wallpapers:download', kwargs={'pk': self.pk})

    def get_full_search_url(self):
        """ Returns the url searching all tags on this wallpaper. """
        tag_slugs = list(self.tags.values_list('slug', flat=True))
        return reverse('wallpapers:list') + "?" + '&'.join('tag='+slug for slug in tag_slugs)

    def get_aspect_ratio(self, as_tuple=False, nearest=True):
        """
        Returns the nearest friendly ratio such as ``16:10``.

        We can find the "nearest" ratio because not all uploads fit perfectly into a standard ratio
        size, but can be set as a wallpaper with simple height cropping.

        """

        divisor = gcd(self.width, self.height)
        rw, rh = (self.width / divisor, self.height / divisor)
        if nearest:
            ratio = sorted(COMMON_ASPECT_RATIOS, key=lambda dim: (rw/rh) / (dim[0]/dim[1]))[-1]
        else:
            ratio = (rw, rh)

        if ratio in FRIENDLY_ASPECT_RATIOS:
            ratio = FRIENDLY_ASPECT_RATIOS[ratio]
        if not as_tuple:
            ratio = ':'.join(map(str, ratio))
        return ratio

    aspect_ratio = property(get_aspect_ratio)

    def get_fractional_aspect_ratio(self):
        ratio = self.get_aspect_ratio()
        x, y = map(Decimal, ratio.split(':'))
        return x / y

    def get_random_stack_tilt(self):
        """ Template UI function that generates a degree rotation value for a "stack". """
        return random.choice(RANDOM_STACK_TILT_ANGLES)

    # Support for wtds.reports app
    @classmethod
    def get_reportable_fields(cls):
        return ('name', 'author', 'license', 'duplicate_of', 'is_public', 'purity_rating', 'tags')

class Author(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, blank=True, null=True)
    name = models.CharField(_('name'), max_length=100, blank=True)
    url = models.URLField(_('url'), max_length=500, blank=True)

    reports = ReportsManager()

    def __str__(self):
        if self.user:
            return str(self.user)
        return self.name or self.url

class License(models.Model):
    name = models.CharField(_('name'), max_length=100)
    short_name = models.CharField(_('short name'), max_length=20)
    summary = models.CharField(_('summary'), max_length=400)

    url = models.URLField(_('url'), max_length=400, blank=True)

    attribute_author = models.BooleanField(_('attribute author'), default=False)
    allow_derivatives = models.BooleanField(_('allow derivatives'), default=False)
    allow_commercial_use = models.BooleanField(_('allow commercial use'), default=False)
    persist_license = models.BooleanField(_('persist license'), default=False)

    def __str__(self):
        return self.name

wtds/core/views.py
from functools import partial

from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.template import RequestContext, Context

class AuthenticationMixin(object):
    login_required = True
    permissions_required = []

    def dispatch(self, request, *args, **kwargs):
        if self.login_required and not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('auth:login'))
        if self.permissions_required:
            if not all(map(self.request.user.has_perm, self.permissions_required)):
                return HttpResponseForbidden()
        return super(AuthenticationMixin, self).dispatch(request, *args, **kwargs)

def _base_error(request, status_code, template_name=None, fake=False):
    context = {'fake': fake}
    try:
        context = RequestContext(request, context)
    except Exception as e:
        context = Context(context)
    response = render_to_response(template_name, context)
    response.status_code = status_code
    return response

handler403 = partial(_base_error, status_code=403, template_name='403.html')
handler404 = partial(_base_error, status_code=404, template_name='404.html')
handler500 = partial(_base_error, status_code=500, template_name='500.html')

wtds/core/templates/OLD_base.html
{% load core_tags i18n %}
{% if not request.is_ajax %}
<!doctype html>
<html>
<head>
    <title>{% block title %}Home{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{{ STATIC_URL }}img/favicon.ico" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/base.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/search.css" />
    {% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/viewing.css" type="text/css" />
    {% endblock css %}
    {% block javascript %}
    <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery-ui-1.10.1.custom.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/base.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/contextmenu.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/switcher.js"></script>
    <script type="text/javascript">
        $(function(){
            if (/webkit/i.test(window.navigator.userAgent)) {
                $('body').addClass('webkit');
            } else {
                if (/opera/i.test(window.navigator.userAgent)) {
                    $('body').addClass('opera');
                } else if (/mozilla/i.test(window.navigator.userAgent)) {
                    $('body').addClass('mozilla');
                }
            }
        });
    </script>
    {% endblock javascript %}
    {% block extra_head %}
        {% combine_forms_media form search_form %}
    {% endblock extra_head %}
</head>
<body class="{% block body_classes %}{% endblock body_classes %}">
    <div id="wrapper">
        <header>
            <menu type="toolbar">
                {% block toolbar %}
                <li><a href="{% url 'tags:list' %}">{% trans "All tags" noop %}</a></li>
                {% endblock toolbar %}
            </menu>

            <div id="settings">
                {% if user.is_authenticated %}
                    <form id="account-control" action="{% url 'profile:switch' %}?next={{ request.path }}?{{ request.GET.urlencode }}" method="post">
                        {% csrf_token %}
                        {{ profile_switch_form.profile.label_tag }}
                        {{ profile_switch_form.profile }}
                        <a id="account" class="tooltip" href="{% url 'profile:view' %}">
                            <span>{% trans "Account" %}</span>
                        </a>
                        {% if perms.wallpapers.add_wallpaper %}
                            <a id="upload" class="tooltip" href="{% url 'wallpapers:upload' %}">
                                <span>{% trans "Upload" %}</span>
                            </a>
                        {% endif %}
                        <a id="logout" class="tooltip" href="{% url 'auth:logout' %}">
                            <span>{% trans "Logout" %}</span>
                        </a>
                    </form>
                {% else %}
                    <div id="account-control">
                        <a href="{% url 'auth:login' %}?next={{ request.path }}">{% trans "Log in" %}</a>
                    </div>
                {% endif %}
            </div>
            <div id="sitename" style="background-image: url({{ logo_wallpaper.image.url }})">
                <a id="logo" href="{% url 'home' %}" style="{# background-image: url({{ logo_wallpaper.image.url }}) #}"></a>
            </div>
        </header>
        <menu id="tile-options" type="context">
            {% block wallpaper_tile_menuitems %}
            <menuitem class="zoom" label="{% trans "Zoom" noop %} " data-url=""></menuitem>
            <menuitem class="download" label="{% trans "Download" noop %}" data-url=""></menuitem>
            <menu id="contextmenu-tags" label="{% trans "Tags" noop %}"></menu>
            {% endblock %}
        </menu>
        <div id="content">
            {% block messages %}
                {% for message in messages %}
                    <p class="message {{ message.tags }}">
                        {{ message }}
                    </p>
                {% endfor %}
            {% endblock messages %}

            <div id="pjax-wrapper">
                {% block search %}{% endblock search %}
                <div id="wrapped-content"> {# Designed to be loaded over ajax #}
{% endif %}
                    {% block content %}{% endblock content %}
{% if not request.is_ajax %}
                </div>
                <div id="stage" class="wallpaper"> {# Designed to contain transitioning content #}
                    {% block stage %}{% endblock stage %}
                </div>
            </div>
        </div>
        <footer>
            <div id="tip">{{ random_tip }}</div>
            <div id="timestamp">
                {% if site_modified_date %}
                    Last site code modification was {{ site_modified_date|timesince }} ago.
                {% else %}
                    We're actually not sure when the last site code modification was.
                    Cron probably isn't generating the file.  Computers, right?
                {% endif %}
            </div>
            <div id="github">
                Website code available at GitHub:
                <a href="https://github.com/tiliv/wtds">https://github.com/tiliv/wtds</a>
            </div>
            <div id="development">
                Powered by <a href="https://www.djangoproject.com/">Django</a>,
                written with <a href="http://blog.macromates.com/2012/textmate-2-at-github/">TextMate 2</a>.
            </div>
            <div id="copyright">
                This website's code is <a href="http://www.gnu.org/licenses/gpl-3.0.html">GPLv3</a>.
                The images belong to their credited author, if any.  Missing author credits should be reported.
            </div>
        </footer>
    </div>
</body>
</html>
{% endif %}

wtds/core/templates/base.html
{% load i18n %}
<!doctype html>
<html lang="en" ng-app="wtds">
<head>
    <title>{% block title %}Home{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{{ STATIC_URL }}img/favicon.ico" />

    {# jQuery #}
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

    {# Bootstrap #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    {# Angular #}
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.min.js"></script>
    {# <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-route.js"></script> #}

    {# scrub libraries all be demandin dis #}
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>

    {# restangular #}
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js"></script>

    {# Core #}
    <script>
        window._STATIC_URL = "{{ STATIC_URL }}";
    </script>
    <script src="{{ STATIC_URL }}app/SiteConfiguration.js"></script>
    <script src="{{ STATIC_URL }}app/HttpQueue.js"></script>
    <script src="{{ STATIC_URL }}app/api.js"></script>
    <script src="{{ STATIC_URL }}app/wallpapers.js"></script>
    <script src="{{ STATIC_URL }}app/app.js"></script>

    <script src="{{ STATIC_URL }}js/base.js"></script>
    <script src="{{ STATIC_URL }}js/resize.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/base.css" />
</head>
<body ng-controller="wtdsController">
    <div id="wrapper">
        <header>
            <menu type="toolbar">
                {% block toolbar %}
                <li><a href="{% url 'tags:list' %}">{% trans "All tags" noop %}</a></li>
                {% endblock toolbar %}
            </menu>

            <div id="settings">
                {% if user.is_authenticated %}
                    <form id="account-control" action="{% url 'profile:switch' %}?next={{ request.path }}?{{ request.GET.urlencode }}" method="post">
                        {% csrf_token %}
                        {{ profile_switch_form.profile.label_tag }}
                        {{ profile_switch_form.profile }}
                        <a id="account" class="tooltip" href="{% url 'profile:view' %}">
                            <span>{% trans "Account" %}</span>
                        </a>
                        {% if perms.wallpapers.add_wallpaper %}
                            <a id="upload" class="tooltip" href="{% url 'wallpapers:upload' %}">
                                <span>{% trans "Upload" %}</span>
                            </a>
                        {% endif %}
                        <a id="logout" class="tooltip" href="{% url 'auth:logout' %}">
                            <span>{% trans "Logout" %}</span>
                        </a>
                    </form>
                {% else %}
                    <div id="account-control">
                        <a href="{% url 'auth:login' %}?next={{ request.path }}">{% trans "Log in" %}</a>
                    </div>
                {% endif %}
            </div>
            <div id="sitename" style="background-image: url({{ logo_wallpaper.image.url }})">
                <a id="logo" href="{% url 'home' %}" style="{# background-image: url({{ logo_wallpaper.image.url }}) #}"></a>
            </div>
        </header>

        <menu id="tile-options" type="context">
            {% block wallpaper_tile_menuitems %}
            <menuitem class="zoom" label="{% trans "Zoom" noop %} " data-url=""></menuitem>
            <menuitem class="download" label="{% trans "Download" noop %}" data-url=""></menuitem>
            <menu id="contextmenu-tags" label="{% trans "Tags" noop %}"></menu>
            {% endblock %}
        </menu>
        <div id="content">
            <div id="wrapped-content">
            {% block content %}{% endblock content %}
            </div>
        </div>

        <footer>
            <div id="tip">{{ random_tip }}</div>
            <div id="timestamp">
                {% if site_modified_date %}
                    Last site code modification was {{ site_modified_date|timesince }} ago.
                {% else %}
                    We're actually not sure when the last site code modification was.
                    Cron probably isn't generating the file.  Computers, right?
                {% endif %}
            </div>
            <div id="github">
                Website code available at GitHub:
                <a href="https://github.com/tiliv/wtds">https://github.com/tiliv/wtds</a>
            </div>
            <div id="development">
                Powered by <a href="https://www.djangoproject.com/">Django</a>,
                written with <a href="http://blog.macromates.com/2012/textmate-2-at-github/">TextMate 2</a>.
            </div>
            <div id="copyright">
                This website's code is <a href="http://www.gnu.org/licenses/gpl-3.0.html">GPLv3</a>.
                The images belong to their credited author, if any.  Missing author credits should be reported.
            </div>
        </footer>
    </div>
</body>
</html>

wtds/core/templates/base_error.html
{% extends "base.html" %}

{% block body_classes %}narrow{% endblock body_classes %}

{% block content %}
    {% if fake %}
        (Faked error)
    {% endif %}
    <h2>{% block error_title %}{% endblock error_title %}</h2>
    {% block error_content %}{% endblock error_content %}
{% endblock content %}

wtds/core/templates/home.html
{% extends "wallpapers/base.html" %}

{% block content %}
    <div id="lineup">
        <wallpaper-list>wallpaper-list</wallpaper-list>
    </div>
{% endblock content %}