wtds/reports/urls.py
"""
URLs for including from other apps.  When included, declare an instance namespace.

"""

from django.conf.urls import patterns, include, url

from .views import ReportListView, ReportCreateView

urlpatterns = patterns('',
    # List views
    url(r'^$', ReportListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/', include(patterns('',
        url(r'^$', ReportListView.as_view(), name="list"),
        url(r'^new/$', ReportCreateView.as_view(), name="create"),
        url(r'^(?P<field_name>[a-z_][a-zA-Z\d_]*)/', include(patterns('',
            url(r'^$', ReportListView.as_view(), name="list"),
            url(r'^new/$', ReportCreateView.as_view(), name="create"),
        )))
    ))),
)

wtds/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
# from django.contrib import admin

from .views import HomeView

# admin.autodiscover()

handler403 = 'wtds.core.views.handler403'
handler404 = 'wtds.core.views.handler404'
handler500 = 'wtds.core.views.handler500'

urlpatterns = patterns('',
    url(r'^api/', include('wtds.urls_api')),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^', include('wtds.wallpapers.urls')),
    url(r'^account/', include('wtds.profile.urls', namespace="profile")),
    url(r'^reports/', include('wtds.reports.management_urls', namespace="reports")),
    
    # auth
    url(r'^', include(patterns('',
        url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
        url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('home')}, name="logout"),
        url(r'^', include('django.contrib.auth.urls')),
    ), namespace='auth')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^~/403/$', handler403, {'fake': True}),
    url(r'^~/404/$', handler404, {'fake': True}),
    url(r'^~/500/$', handler500, {'fake': True}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^{}(?P<path>.*)$'.format(settings.MEDIA_URL.lstrip('/')), 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        })
    )

wtds/wallpapers/urls.py
from django.conf.urls import patterns, url, include

from wtds.reports import include_reports_urls
from .views import (WallpaperCreateView, WallpaperUpdateView, WallpaperDetailView,
        WallpaperDeleteView, WallpaperListView, TagListView, TagOrphanedListView, TagUpdateView,
        TagDeleteView, TagAutocompleteView)

urlpatterns = patterns('',
    url(r'^wallpapers/', include(patterns('',
        # Filtered views
        url(r'^$', WallpaperListView.as_view(), name="list"),
        url(r'^(?P<ratio>\d+:\d+)/$', WallpaperListView.as_view(), name="list"),

        # Special filtered views
        url(r'^in-danger/', include(patterns('',
            url(r'^$', WallpaperListView.as_view(in_danger=True), name="in_danger"),
            url(r'^(?P<slug>[\w-]+)/$', WallpaperListView.as_view(in_danger=True), name="in_danger"),
        ))),

        url(r'^new/$', WallpaperCreateView.as_view(), name="upload"),
        url(r'^(?P<pk>\d+)/', include(patterns('',
            url(r'^$', WallpaperDetailView.as_view(), name="view"),
            url(r'^download/$', WallpaperDetailView.as_view(download=True), name="download"),
            url(r'^edit/$', WallpaperUpdateView.as_view(), name="edit"),
            url(r'^delete/$', WallpaperDeleteView.as_view(), name="delete"),
        ))),

        # Reports
        include_reports_urls('wallpaper'),
        # url(r'^reports/', include('wtds.reports.urls', namespace="reports", app_name='wallpapers')),
    ), namespace="wallpapers")),

    url(r'^tags/', include(patterns('',
        url(r'^$', TagListView.as_view(), name="list"),
        url(r'^orphaned/$', TagOrphanedListView.as_view(), name="orphaned"),
        url(r'^autocomplete/$', TagAutocompleteView.as_view(), name="autocomplete"),
        url(r'^inspect/(?P<slug>[\w-]+)/', include(patterns('',
            url(r'^edit/$', TagUpdateView.as_view(), name="edit"),
            url(r'^delete/$', TagDeleteView.as_view(), name="delete"),
        ))),
    ), namespace="tags")),
)

wtds/wallpapers/models.py
from fractions import gcd
import random
from operator import itemgetter
import logging
from decimal import Decimal

from django.db import models
from django.db.models import Avg, F
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.generic import GenericRelation
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from taggit.models import TagBase, GenericTaggedItemBase
from taggit.managers import TaggableManager

from wtds.reports import ReportsManager
from .managers import TagManager, WallpaperManager
from .constants import (COMMON_ASPECT_RATIOS, FRIENDLY_ASPECT_RATIOS, RANDOM_STACK_TILT_ANGLES,
        PURITY_CHOICES, MIN_PURITY_RATING, MAX_PURITY_RATING)

logger = logging.getLogger(__name__)

class Tag(TagBase):
    """ Adds a purity rating to the existing taggit ``Tag`` model. """
    purity_rating = models.FloatField(_('purity rating'), default=0, editable=False)

    objects = TagManager()

    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('wallpapers:list') + "?tag={}".format(self.slug)
    
    def get_wallpapers(self):
        """ Due to the generic relation between this and ``Wallpaper`` this method eases lookup. """
        return Wallpaper.objects.filter(tags=self)
    
    def get_wallpapers_with_this_tag_only(self):
        """ Returns ``Wallpaper`` objects whose only tag is this one. """
        return Wallpaper.objects.filter_by_orphan_danger(tags=self)

    def get_purity_rating_display(self):
        """ Fakes the normal API for a ``choices`` field. """
        try:
            return PURITY_CHOICES[int(round(self.purity_rating))][1]
        except IndexError:
            rating = self.purity_rating
            self.purity_rating = min(max(self.purity_rating, MIN_PURITY_RATING), MAX_PURITY_RATING)
            logger.error("Tag %r has a purity rating %r outside of the valid range %d-%d."
                    "Normalizing to %d.", self, rating, MIN_PURITY_RATING, MAX_PURITY_RATING,
                    self.purity_rating)
            self.save()

class TaggedWallpaper(GenericTaggedItemBase):
    """ A replacement ``Tag`` model for taggit's API. """
    tag = models.ForeignKey('Tag', related_name="%(app_label)s_%(class)s_items")

class Wallpaper(models.Model):
    objects = WallpaperManager()

    name = models.CharField(_('Name'), max_length=100, blank=True,
            help_text=_("If left blank, the tags will be shown."))
    image = models.ImageField(_('Image'), upload_to='%Y/%m/%d', height_field='height',
            width_field='width')
    height = models.PositiveIntegerField(_('Height'))
    width = models.PositiveIntegerField(_('Width'))
    raw_ratio = models.CharField(max_length=50)
    fractional_ratio = models.DecimalField(max_digits=11, decimal_places=10)
    # color_profile = models.CharField()

    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('uploader'),
            help_text=_("Contributing user account"))
    author = models.ForeignKey('Author', verbose_name=_('Author'), blank=True, null=True,
            help_text=_("Original creator"))
    license = models.ForeignKey('License', verbose_name=_('License'), default=8)
    duplicate_of = models.ForeignKey('self', verbose_name=_('Duplicate'), blank=True, null=True)
    date_created = models.DateTimeField(_('Date created'), auto_now_add=True)
    is_public = models.BooleanField(_('Public'), default=True)
    purity_rating = models.IntegerField(_('Purity'), choices=PURITY_CHOICES, default=0)

    views = models.PositiveIntegerField(_('Views'), default=0)
    tags = TaggableManager(_('Tags'), blank=False, through=TaggedWallpaper)

    reports = ReportsManager()

    class Meta:
        get_latest_by = 'date_created'

    def __str__(self):
        if self.name:
            return self.name
        return ", ".join(map(str, self.tags.all()))

    def clean(self):
        if self.duplicate_of and self.duplicate_of is self:
            raise ValidationError("Wallpaper can't be marked as a duplicate of itself.")

    def save(self, *args, **kwargs):
        """ Pre-bake the ratio. """
        self.raw_ratio = self.get_aspect_ratio()
        self.fractional_ratio = self.get_fractional_aspect_ratio()
        super(Wallpaper, self).save(*args, **kwargs)

    def assess_tag_purity(self):
        """ Visits each tag and crunches the average purity rating of its wallpapers. """
        return
        # AVG = Avg('wallpapers_taggedwallpaper_items__wallpaper__purity_rating')
        # tags = self.tags.annotate(purity_avg=AVG).exclude(purity_avg=F('purity_rating'))
        # for tag in tags:
        #     logger.info("Tag %r changing purity rating from %r to %r", tag, tag.purity_rating,
        #             tag.purity_avg)
        #     tag.purity_rating = tag.purity_avg
        #     tag.save()

    def get_absolute_url(self):
        return reverse('wallpapers:view', kwargs={'pk': self.pk})

    def get_download_url(self):
        return reverse('wallpapers:download', kwargs={'pk': self.pk})

    def get_full_search_url(self):
        """ Returns the url searching all tags on this wallpaper. """
        tag_slugs = list(self.tags.values_list('slug', flat=True))
        return reverse('wallpapers:list') + "?" + '&'.join('tag='+slug for slug in tag_slugs)

    def get_aspect_ratio(self, as_tuple=False, nearest=True):
        """
        Returns the nearest friendly ratio such as ``16:10``.

        We can find the "nearest" ratio because not all uploads fit perfectly into a standard ratio
        size, but can be set as a wallpaper with simple height cropping.

        """

        divisor = gcd(self.width, self.height)
        rw, rh = (self.width / divisor, self.height / divisor)
        if nearest:
            ratio = sorted(COMMON_ASPECT_RATIOS, key=lambda dim: (rw/rh) / (dim[0]/dim[1]))[-1]
        else:
            ratio = (rw, rh)

        if ratio in FRIENDLY_ASPECT_RATIOS:
            ratio = FRIENDLY_ASPECT_RATIOS[ratio]
        if not as_tuple:
            ratio = ':'.join(map(str, ratio))
        return ratio

    aspect_ratio = property(get_aspect_ratio)

    def get_fractional_aspect_ratio(self):
        ratio = self.get_aspect_ratio()
        x, y = map(Decimal, ratio.split(':'))
        return x / y

    def get_random_stack_tilt(self):
        """ Template UI function that generates a degree rotation value for a "stack". """
        return random.choice(RANDOM_STACK_TILT_ANGLES)

    # Support for wtds.reports app
    @classmethod
    def get_reportable_fields(cls):
        return ('name', 'author', 'license', 'duplicate_of', 'is_public', 'purity_rating', 'tags')

class Author(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, blank=True, null=True)
    name = models.CharField(_('name'), max_length=100, blank=True)
    url = models.URLField(_('url'), max_length=500, blank=True)

    reports = ReportsManager()

    def __str__(self):
        if self.user:
            return str(self.user)
        return self.name or self.url

class License(models.Model):
    name = models.CharField(_('name'), max_length=100)
    short_name = models.CharField(_('short name'), max_length=20)
    summary = models.CharField(_('summary'), max_length=400)

    url = models.URLField(_('url'), max_length=400, blank=True)

    attribute_author = models.BooleanField(_('attribute author'), default=False)
    allow_derivatives = models.BooleanField(_('allow derivatives'), default=False)
    allow_commercial_use = models.BooleanField(_('allow commercial use'), default=False)
    persist_license = models.BooleanField(_('persist license'), default=False)

    def __str__(self):
        return self.name

wtds/reports/views.py
import logging

from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.contenttypes.models import ContentType

from wtds.core.views import AuthenticationMixin
from .models import Report
from .forms import ReportForm

logger = logging.getLogger(__name__)

class ReportMixin(AuthenticationMixin):
    model = Report

    target_content_type = None
    target_model_class = None
    target_model_field_name = None
    target_model_instance_pk = None
    target_model_instance = None

    def dispatch(self, request, *args, **kwargs):
        self._resolve_target(request, kwargs)
        return super(ReportMixin, self).dispatch(request, *args, **kwargs)

    def _resolve_target(self, request, kwargs):
        """
        Sets the view's attributes if the corresponding url keyword arguments are available:

        * content type (and model class, by association)
        * field name
        * instance

        """

        instance_name = request.resolver_match.app_name # dispatch from embedded app urls
        if instance_name or 'contenttype' in kwargs:
            if instance_name:
                model = instance_name
            elif 'contenttype' in kwargs:
                model = kwargs['contenttype']

            # ContentType
            self.target_content_type = ContentType.objects.get(model=model)

            # Model class
            self.target_model_class = self.target_content_type.model_class()

            # Model field
            if 'field_name' in kwargs:
                # TODO: Catch abuse of field lookups
                field = self.target_model_class._meta.get_field_by_name(kwargs['field_name'])[0]
                self.target_model_field_name = field.name

            # Model instance
            if 'model_pk' in kwargs:
                self.target_model_instance_pk = kwargs['model_pk']
            elif 'pk' in kwargs: # dispatch from embedded app urls
                self.target_model_instance_pk = kwargs['pk']
            if self.target_model_instance_pk is not None:
                self.target_model_instance = self.target_model_class.objects.get(
                        pk=self.target_model_instance_pk)

        # reports_fieldname = None
        # # Inspect the Report model's reverse relationships and find the field name being used on the target model. Typically this would be "reports", as in "MyModel.reports"
        # for rel, _model in self.model._meta.get_all_related_m2m_objects_with_model():
        #     if rel.model == model_class:
        #         reports_fieldname = rel.field.name
        #         break
        # else:
        #     # FIXME: This error can be raised by any client requesting a contenttype name that simply doesn't leverage the reports app.
        #     msg = "%r doesn't declare a relationship to %r" % (self.target_model_class, self.model)
        #     raise ValueError(msg)

    def get_queryset(self):
        queryset = self.model.objects.all()
        if self.target_content_type:
            queryset = queryset.filter(content_type=self.target_content_type)
            if self.target_model_field_name:
                queryset = queryset.filter(object_fieldname=self.target_model_field_name)
        return queryset

    def get_object(self):
        return self.target_model_instance

    def get_context_data(self, **kwargs):
        context = super(ReportMixin, self).get_context_data(**kwargs)
        if self.target_model_instance:
            context[self.target_model_class._meta.module_name] = self.target_model_instance
            context.update({
                'content_type': self.target_content_type,
                'model': self.target_model_class,
                'field_name': self.target_model_field_name,
                'instance': self.target_model_instance,
            })
        return context

    def get_template_names(self):
        template_names = [self.template_name]
        if self.target_model_class:
            template_names = [
                'reports/{}{}.html'.format(self.target_model_class._meta.module_name, self.template_name_suffix),
                '{}/report{}.html'.format(self.target_model_class._meta.module_name + 's', self.template_name_suffix),
            ] + template_names
        return template_names

class ReportListView(ReportMixin, ListView):
    permissions_required = ['reports.change_report']
    template_name = 'reports/report_list.html'

    def get_context_data(self, **kwargs):
        context = super(ReportListView, self).get_context_data(**kwargs)
        context.update({
            'model': self.target_model_class.__name__ if self.target_model_class else None,
            'content_type': self.target_content_type,
            'instance': self.target_model_instance,
        })
        return context

class ReportDetailView(ReportMixin, DetailView):
    permissions_required = ['reports.change_report']
    template_name = 'reports/report_detail.html'


class ReportFormMixin(object):
    form_class = ReportForm
    template_name = 'reports/report_form.html'

    def get_initial(self):
        return {
            'content_type': self.target_content_type,
            'object_id': self.target_model_instance_pk,
            'object_fieldname': self.target_model_field_name,
        }

    def get_form_kwargs(self):
        kwargs = super(ReportFormMixin, self).get_form_kwargs()
        kwargs.update({
            'model': self.target_model_class,
        })
        return kwargs
    
class ReportCreateView(ReportMixin, ReportFormMixin, CreateView):
    # permissions_required = ['reports.add_report']
    pass

class ReportUpdateView(ReportMixin, ReportFormMixin, UpdateView):
    permissions_required = ['reports.change_report']

wtds/wallpapers/templates/wallpapers/base.html
{% extends "base.html" %}

wtds/wallpapers/templates/wallpapers/base_searchable.html
{% extends "base.html" %}

{% block search %}
    {% include "wallpapers/includes/search_bar.html" %}
{% endblock search %}

wtds/wallpapers/templates/wallpapers/report_form.html
{% extends "reports/report_form.html" %}

{% block reported_object_preview %}
    {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
{% endblock reported_object_preview %}

wtds/wallpapers/templates/wallpapers/tag_confirm_delete.html
{% extends "wallpapers/base.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}Delete tag '{{ object }}'?{% endblocktrans %}{% endblock title %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" type="text/css" />
{% endblock css %}

{% block content %}
{% with wallpapers=object.get_wallpapers orphaned=object.get_wallpapers_with_this_tag_only %}
    {{ block.super }}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if wallpapers %}
            <p class="message warning">
                {% blocktrans count counter=wallpapers|length %}
                Deleting this tag will remove it from the {{ counter }} wallpaper shown below.
                {% plural %}
                Deleting this tag will remove it from the {{ counter }} wallpapers shown below.
                {% endblocktrans %}
            </p>

            {% if orphaned %}
                <p class="message warning">
                    {% blocktrans count counter=orphaned|length %}
                    One wallpaper is using this as its only tag.
                    This tag cannot be deleted until this wallpaper is given an additional tag.
                    The wallpaper is found here:
                    {% plural %}
                    {{ counter }} wallpapers are using this as their only tag.
                    This tag cannot be deleted until these wallpapers are given an additional tag.
                    The wallpapers are found here:
                    {% endblocktrans %}
                    {% url 'wallpapers:in_danger' tag.slug as danger_url %}
                    <a href="{{ danger_url }}">{{ danger_url }}</a>
                </p>
            {% endif %}
        {% else %}
            <p class="message info">
                {% trans "This tag is unused, and deleting it will have no side effects." %}
            </p>
        {% endif %}
        <p>
            {% blocktrans %}Are you sure you want to delete the '{{ tag }}' tag?{% endblocktrans %}
        </p>
        <p>
            <input type="submit" value="Delete"{% if orphaned %} disabled="disabled"{% endif %} />
        </p>
    </form>

    {% if wallpapers %}
        <h2>
            {% blocktrans count counter=wallpapers|length %}
                {{ counter }} wallpaper currently tagged:
            {% plural %}
                {{ counter }} wallpapers currently tagged:
            {% endblocktrans %}
        </h2>
        {% for wallpaper in wallpapers %}
            {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
        {% endfor %}
    {% endif %}
{% endwith %}
{% endblock content %}

wtds/wallpapers/templates/wallpapers/tag_form.html
{% extends "wallpapers/base.html" %}

{% block title %}Edit tag '{{ object }}'{% endblock title %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" type="text/css" />
{% endblock css %}

{% block content %}
    {{ block.super }}
    <form action="" method="post">
        {% csrf_token %}
        <p>
            <input type="submit" value="Save" />
        </p>
        {{ form.as_p }}
    </form>

    {% with wallpapers=object.get_wallpapers %}
        <h2>{{ wallpapers|length }} wallpaper{{ wallpapers|pluralize }} currently tagged:</h2>
        {% for wallpaper in wallpapers %}
            {% include "wallpapers/includes/tile.html" with wallpaper=wallpaper only %}
        {% endfor %}
    {% endwith %}
{% endblock content %}

wtds/wallpapers/templates/wallpapers/tag_list.html
{% extends "wallpapers/base.html" %}

{% block title %}{% spaceless %}
    {% if view.orphaned %}
        Orphaned tags
    {% else %}
        All tags
    {% endif %}
{% endspaceless %}{% endblock title %}

{% block toolbar %}
    {{ block.super }}
    <li><a href="{% url 'tags:orphaned' %}">View orphaned tags</a></li>
{% endblock toolbar %}

{% block content %}
    {{ block.super }}

    <h2>{% if view.orphaned %}Orphaned {% endif %}Tags</h2>

    <ul>
        {% regroup object_list by get_purity_rating_display as tag_groups %}
        {% for tags in tag_groups %}
            <li>
                Purity: {{ tags.grouper }}
                <ul>
                    {% for tag in tags.list %}
                    <li>
                        {% include "wallpapers/includes/single_tag_link.html" with tag=tag only %}
                        <a class="button" href="{% url 'tags:edit' tag.slug %}">Edit</a>
                        <a class="button" href="{% url 'tags:delete' tag.slug %}">Delete</a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

wtds/wallpapers/templates/wallpapers/wallpaper_confirm_delete.html
{% extends "wallpapers/base.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}Delete '{{ object }}'?{% endblocktrans %}{% endblock title %}

{% block content %}
    <form action="{% url 'wallpapers:delete' object.pk %}" method="post">
        {% csrf_token %}
        <img src="{{ object.image.url }}" width="200px" style="float: left; margin: 0 1em 1em 0;" />
        {% if not object.duplicate_of %}
            <p class="message warning" style="margin-left: 215px">{% trans "WARNING: This image is not marked as being a duplicate." %}</p>
        {% endif %}
        {% if object.name %}
            <h2>{{ object.name }}</h2>
        {% endif %}

        <p>
            {% include "wallpapers/includes/tags_as_links.html" with tags=object.tags.all only %}
        </p>
        <p>{% trans "Delete this wallpaper?" noop %}</p>
        <p>
            <input type="submit" value="Delete" />
        </p>
    </form>
{% endblock content %}

wtds/wallpapers/templates/wallpapers/wallpaper_detail.html
{% extends "wallpapers/base_searchable.html" %}
{% load i18n %}

{% block title %}{% trans "Wallpaper" %}: {{ object }}{% endblock title %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/calculate-gcd-javascript.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/resize.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/viewing.js"></script>
{% endblock javascript %}

{% block stage %}
    <img src="{{ object.image.url }}" />
{% endblock stage %}

{% block content %}
    <aside id="details">
        {% if perms.wallpaper.change_wallpaper and object.tags.all|length == 1 %}
            <p class="message warning">{% trans "This wallpaper has only one tag." %}</p>
        {% endif %}

        {% spaceless %}
        <div id="actions">
            <div class="buttons-strip">
                {% if user.is_staff or perms.wallpapers.change_wallpaper and object.uploader == user %}
                    <a rel="edit" href="{% url 'wallpapers:edit' object.pk %}" title="{% trans "Edit" %}"><span /></a>
                {% endif %}
                {% if user.is_staff or perms.wallpapers.delete_wallpaper %}
                    <a rel="delete" href="{% url 'wallpapers:delete' object.pk %}" title="{% trans "Delete" %}"><span /></a>
                {% endif %}
                <a rel="download" href="{% url "wallpapers:download" object.pk %}" title="{% trans "Download" %}"><span /></a>
                <a rel="favorite"
                        {% if object.is_favorite %}
                        title="{% trans "Remove from favorites" %}" class="active"
                        href="{% url "profile:favorites:remove" object.pk %}"
                        {% else %}
                        title="{% trans "Add to favorites" %}"
                        href="{% url "profile:favorites:add" object.pk %}"
                        {% endif %}><span /></a>
            </div>
        </div>
        {% endspaceless %}

        <p class="name{% if not object.name %} hidden{% endif %}">
            <label title="{% trans "Name" %}"></label>
            <span>{{ object.name }}</span>
        </p>
        <p class="tags">
            <label title="{% trans "Tags" %}"></label>
            <span>{% include "wallpapers/includes/tags_as_links.html" with tags=object.tags.all only %}</span>
        </p>
        <p class="purity {{ wallpaper.get_purity_rating_display|slugify }}">
            <label title="{% trans "Purity" %}"></label>
            <span>{{ wallpaper.get_purity_rating_display }}</span>
        </p>
        <p class="size">
            <label title="{% trans "Dimensions" %}"></label>
            <span>{{ object.width }} &times; {{ object.height }}</span>
            (<span class="showing"></span>% {% trans "actual size" %})
        </p>
        <p class="aspect-ratio">
            <label title="{% trans "Aspect ratio" %}"></label>
            <span>{{ object.aspect_ratio }}</span>
        </p>
        <p class="uploader">
            <label title="{% trans "Uploader" %}"></label>
            <span>{{ object.uploader }}</span>
        </p>
        <p class="author">
            <label title="{% trans "Author" %}"></label>
            {% if object.author %}
                <span>{{ object.author }}</span>
            {% else %}
                <span>{% trans "Unknown" %}</span>
                <a href="{% url 'wallpapers:reports:create' pk=object.pk field_name='author' %}">Tip us off if you know!</a>
            {% endif %}
        </p>

        <div id="similar">
            <h4>{% trans "Similar by:" %}</h4>
            <div class="related tags">
                <h5>{% trans "tags" %}</h5>
                {% if similar.tags.0 %}
                {% include "wallpapers/includes/tile.html" with wallpaper=similar.tags.0 stack=similar.tags.1 only %}
                {% endif %}
            </div>
            <div class="related color">
                <h5>{% trans "color" %}</h5>
                {% if similar.color.0 %}
                {% include "wallpapers/includes/tile.html" with wallpaper=similar.color.0 stack=similar.color.1 only %}
                {% endif %}
            </div>
            <div class="related size">
                <h5>{% trans "size" %}</h5>
                {% if similar.size.0 %}
                {% include "wallpapers/includes/tile.html" with wallpaper=similar.size.0 stack=similar.size.1 only %}
                {% endif %}
            </div>
            <div class="clear">&nbsp;</div>
        </div>

    </aside>
{% endblock content %}